name: bit_flow
description: "Downloader Manager"
publish_to: 'none'
version: 1.2.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  clipboard: ^0.1.3
  dropdown_button2: ^2.3.9
  path: ^1.9.1
  url_launcher: ^6.3.1
  file_picker: ^10.2.0
  http: ^1.4.0
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  get: ^4.7.2
  font_awesome_flutter: ^10.8.0
  hotkey_manager: ^0.2.3
  msix: ^3.16.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: "PuHui"
      fonts:
        - asset: fonts/AlibabaPuHuiTi-3-Regular.ttf
          weight: 400
        - asset: fonts/AlibabaPuHuiTi-3-Bold.ttf
          weight: 700
  assets:
    - assets/

msix_config:
  display_name: Bit Flow
  publisher_display_name: ZhouCheng
  identity_name: ZhouCheng.BitFlow
  msix_version: 1.2.1.0
  logo_path: assets/icon.png
  trim_logo: false
  capabilities: internetClient, internetClientServer
  languages: zh-cn, zh-tw, en-us
  publisher: # Publisher HERE
  store: true